/*
 * adaptivecards-templating-service-javascript-sdk
 * Adaptive Cards Templating Service API definition.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AdaptivecardsTemplatingServiceJavascriptSdk);
  }
}(this, function(expect, AdaptivecardsTemplatingServiceJavascriptSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AdaptivecardsTemplatingServiceJavascriptSdk.TemplateApi();
  });

  describe('(package)', function() {
    describe('TemplateApi', function() {
      describe('templateById', function() {
        it('should call templateById successfully', function(done) {
          // TODO: uncomment, update parameter values for templateById call and complete the assertions
          /*
          var templateId = "templateId_example";

          instance.templateById(templateId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AdaptivecardsTemplatingServiceJavascriptSdk.Template);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("");
            expect(data.template).to.be.a('string');
            expect(data.template).to.be("");
            expect(data.isPublished).to.be.a('boolean');
            expect(data.isPublished).to.be(false);
            expect(data.createdAt).to.be.a('string');
            expect(data.createdAt).to.be("");
            expect(data.owner).to.be.a('string');
            expect(data.owner).to.be("");
            {
              let dataCtr = data.tags;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a('string');
                expect(data).to.be("");
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('templateGet', function() {
        it('should call templateGet successfully', function(done) {
          // TODO: uncomment templateGet call and complete the assertions
          /*

          instance.templateGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AdaptivecardsTemplatingServiceJavascriptSdk.TemplateList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('templatePost', function() {
        it('should call templatePost successfully', function(done) {
          // TODO: uncomment, update parameter values for templatePost call
          /*
          var body = new AdaptivecardsTemplatingServiceJavascriptSdk.NewTemplate();
          body.template = "";
          body.isPublished = false;

          instance.templatePost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
