import { Template } from 'adaptive-templating-service-typescript-node';

import { IncomingMessage } from "http";

export interface CurrentTemplateState {
  templateID?: string;
  templateJSON?: object;
  templateName?: string;
  sampleDataJSON?: object;
  template?: Template;
  isFetching: boolean;
  isFetchingTags: boolean;
  version?: string;
}

//Action Types
export const NEW_TEMPLATE = 'NEW_TEMPLATE';
export const REQUEST_NEW_TEMPLATE_UPDATE = 'REQUEST_NEW_TEMPLATE_UPDATE';
export const RECEIVE_NEW_TEMPLATE_UPDATE = 'RECEIVE_NEW_TEMPLATE_UPDATE';
export const FAILURE_NEW_TEMPLATE_UPDATE = 'FAILURE_NEW_TEMPLATE_UPDATE';

export const REQUEST_EXISTING_TEMPLATE_UPDATE = 'REQUEST_EXISTING_TEMPLATE_UPDATE';
export const RECEIVE_EXISTING_TEMPLATE_UPDATE = 'RECEIVE_EXISTING_TEMPLATE_UPDATE';
export const FAILURE_EXISTING_TEMPLATE_UPDATE = 'FAILURE_EXISTING_TEMPLATE_UPDATE';
export const RECEIVE_EXISTING_TEMPLATE_STATE_UPDATE = 'RECEIVE_EXISTING_TEMPLATE_STATE_UPDATE';

export const REQUEST_EXISTING_TEMPLATE_UPDATE_TAGS = 'REQUEST_EXISTING_TEMPLATE_UPDATE_TAGS';
export const RECIEVE_EXISTING_TEMPLATE_UPDATE_TAGS = 'RECIEVE_EXISTING_TEMPLATE_UPDATE_TAGS';
export const FAILURE_EXISTING_TEMPLATE_UPDATE_TAGS = 'FAILURE_EXISTING_TEMPLATE_UPDATE_TAGS';

export const REQUEST_UPDATE_CURRENT_TEMPLATE_VERSION = 'REQUEST_UPDATE_CURRENT_TEMPLATE_VERSION';
export const RECEIVE_UPDATE_CURRENT_TEMPLATE_VERSION = 'RECEIVE_UPDATE_CURRENT_TEMPLATE_VERSION';
export const FAILURE_UPDATE_CURRENT_TEMPLATE_VERSION = 'FAILURE_UPDATE_CURRENT_TEMPLATE_VERSION';

export const GET_TEMPLATE = 'GET_TEMPLATE';
export const GET_TEMPLATE_TAGS = 'GET_TEMPLATE_TAGS';
export const GET_TEMPLATE_SUCCESS = 'GET_TEMPLATE_SUCCESS';
export const GET_TEMPLATE_FAILURE = 'GET_TEMPLATE_FAILURE';

export const DELETE_TEMPLATE_INSTANCE = 'DELETE_TEMPLATE_INSTANCE';
export const DELETE_TEMPLATE_INSTANCE_SUCCESS = 'DELETE_TEMPLATE_INSTANCE_SUCCESS';
export const DELETE_TEMPLATE_INSTANCE_FAILURE = 'DELETE_TEMPLATE_INSTANCE_FAILURE';


export type CurrentTemplateActionTypes = typeof NEW_TEMPLATE |
  typeof REQUEST_NEW_TEMPLATE_UPDATE |
  typeof RECEIVE_NEW_TEMPLATE_UPDATE |
  typeof FAILURE_NEW_TEMPLATE_UPDATE |
  typeof REQUEST_EXISTING_TEMPLATE_UPDATE |
  typeof RECEIVE_EXISTING_TEMPLATE_UPDATE |
  typeof FAILURE_EXISTING_TEMPLATE_UPDATE |
  typeof RECEIVE_EXISTING_TEMPLATE_STATE_UPDATE |
  typeof REQUEST_EXISTING_TEMPLATE_UPDATE_TAGS |
  typeof RECIEVE_EXISTING_TEMPLATE_UPDATE_TAGS |
  typeof FAILURE_EXISTING_TEMPLATE_UPDATE_TAGS |
  typeof REQUEST_UPDATE_CURRENT_TEMPLATE_VERSION |
  typeof RECEIVE_UPDATE_CURRENT_TEMPLATE_VERSION |
  typeof FAILURE_UPDATE_CURRENT_TEMPLATE_VERSION |
  typeof GET_TEMPLATE |
  typeof GET_TEMPLATE_TAGS |
  typeof GET_TEMPLATE_SUCCESS |
  typeof GET_TEMPLATE_FAILURE |
  typeof DELETE_TEMPLATE_INSTANCE |
  typeof DELETE_TEMPLATE_INSTANCE_SUCCESS |
  typeof DELETE_TEMPLATE_INSTANCE_FAILURE;

export interface CurrentTemplateAction {
  type: CurrentTemplateActionTypes;
  text: string;
  templateID?: string;
  templateJSON?: object;
  templateName?: string;
  sampleDataJSON?: object;
  template?: Template;
  version?: string;
  error?: IncomingMessage;
}
