
trigger:
  batch: true
  branches:
    include:
    - dev
    - stage
    - users/daniellemott/add_policheck
    # exclude:
    # - users/*

# trigger: none

# pr:
#   branches:
#     include:
#     - dev
#     exclude:
#     - stage
#     - users/*

variables: 
  ## Add this under variables section in the pipeline
  azureSubscription: 'Adaptive Cards (47c80630-3d74-4b3e-a2f4-57e6368cd8c6)'
  keyVault: 'AC-KeyVault-West'

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: PoliCheck@1
    inputs:
      inputType: 'Basic'
      targetType: 'F'
      targetArgument: '$(system.defaultworkingdirectory)/private-templates-service'
      result: 'PoliCheck.xml'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(system.defaultworkingdirectory)/private-templates-service'
      ArtifactName: 'PoliCheck.xml'
      publishLocation: 'Container'

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: $(azureSubscription)
      keyVaultName: $(keyVault)
      secretsFilter: 'DevACMSSecret'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
          Write-Host "##vso[task.setvariable variable=ACMS_APP_SECRET;]$(DevACMSSecret)"

  - task: NodeTool@0 
    inputs:
      versionSpec: '12.x'

  - script: |
      cd private-templates-service/server
      npm run init-app
      cd ../client
      npm run build
    displayName: Build App

  - script: |
      cd private-templates-service/client
      npm run test
    displayName: Run frontend tests
      
  - script: |
      cd private-templates-service/adaptivecards-templating-service
      npm install
      npm run build
      npm run test
    displayName: Run backend tests

  - script: |
      cd private-templates-service/server
      npm run deploy
    displayName: Build backend