/*
 * adaptivecards-templating-service-javascript-sdk
 * Adaptive Cards Templating Service API definition.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AdaptivecardsTemplatingServiceJavascriptSdk);
  }
}(this, function(expect, AdaptivecardsTemplatingServiceJavascriptSdk) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('BaseError', function() {
      beforeEach(function() {
        instance = new AdaptivecardsTemplatingServiceJavascriptSdk.BaseError();
      });

      it('should create an instance of BaseError', function() {
        // TODO: update the code to test BaseError
        expect(instance).to.be.a(AdaptivecardsTemplatingServiceJavascriptSdk.BaseError);
      });

      it('should have the property error (base name: "error")', function() {
        // TODO: update the code to test the property error
        expect(instance).to.have.property('error');
        // expect(instance.error).to.be(expectedValueLiteral);
      });

    });
  });

}));
