/*
 * adaptivecards-templating-service-javascript-sdk
 * Adaptive Cards Templating Service API definition.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NewTemplate', 'model/Template', 'model/TemplateList', 'api/TemplateApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/NewTemplate'), require('./model/Template'), require('./model/TemplateList'), require('./api/TemplateApi'));
  }
}(function(ApiClient, NewTemplate, Template, TemplateList, TemplateApi) {
  'use strict';

  /**
   * Adaptive_Cards_Templating_Service_API_definition_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var AdaptivecardsTemplatingServiceJavascriptSdk = require('index'); // See note below*.
   * var xxxSvc = new AdaptivecardsTemplatingServiceJavascriptSdk.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new AdaptivecardsTemplatingServiceJavascriptSdk.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new AdaptivecardsTemplatingServiceJavascriptSdk.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new AdaptivecardsTemplatingServiceJavascriptSdk.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The NewTemplate model constructor.
     * @property {module:model/NewTemplate}
     */
    NewTemplate: NewTemplate,
    /**
     * The Template model constructor.
     * @property {module:model/Template}
     */
    Template: Template,
    /**
     * The TemplateList model constructor.
     * @property {module:model/TemplateList}
     */
    TemplateList: TemplateList,
    /**
     * The TemplateApi service constructor.
     * @property {module:api/TemplateApi}
     */
    TemplateApi: TemplateApi
  };

  return exports;
}));
