name: run-test-suites

on:
    push:
        branches:
            - users/daniellemott/must_pass_tests

jobs:
    run-test-suites:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.0.0
              with:
                  ref: users/daniellemott/must_pass_tests
            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - name: Backend Jest Test
              run: |
                  cd private-templates-service/server
                  npm install
                  npm run test
                  cd ..
            - name: Frontend Jest Test
              run: |
                  cd private-templates-service/client
                  npm install
                  npm run test
                  cd ..
            - name: npm install and npm build
              if: success()
              run: |
                  # Build and test the project, then
                  # deploy to Azure Web App.
                  cd private-templates-service/client
                  npm run build:dev --if-present
